pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                    credentialsId: '77574aa6-ebb8-4641-9540-da90dbcb1576',
                    url: 'https://github.com/Rohitcs09/MLOPS.git'
            }
        }

        stage('Build with Maven') {
            steps {
                script {
                    def status = sh(
                        script: """
                            cd ai-projects/hybrid-self-healing-agent
                            echo "🚀 Running Maven Build..."
                            mvn clean install
                        """,
                        returnStatus: true
                    )

                    if (status != 0) {
                        echo "❌ Build Failed"
                        error("Maven Build Failed")
                    } else {
                        echo "✅ Build Passed"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "🎉 Pipeline Completed Successfully"
        }
        failure {
            echo "💥 Pipeline Failed"
        }
    }
}
